// BLOGS
export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAILURE = "BLOG_LIST_FAILURE";

// GET BLOGS
export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE";

// GET_POPULAR
export const GET_PUPULAR_BLOG_LIST_REQUEST = "GET_PUPULAR_BLOG_LIST_REQUEST";
export const GET_PUPULAR_BLOG_LIST_SUCCESS = "GET_PUPULAR_BLOG_LIST_SUCCESS";
export const GET_PUPULAR_BLOG_LIST_FAILURE = "GET_PUPULAR_BLOG_LIST_FAILURE";